### ISSUE TITLE
Deprecation warning on some choices

### ISSUE THREAD

**Issue by joewhite101** [jhipster/generator-jhipster-quarkus#84] opened 2020-09-12 18:34 UTC
**Describe the bug**
When running the blueprint in some cases the user will get:

```
WARNING! Deprecated: JHipster seems to be invoked using Yeoman command. Please use the JHipster CLI. Run jhipster <command> instead of yo jhipster:<command>
```

**To Reproduce**
Run on master.  Select the choices below.

```
? Would you like to use Maven or Gradle for building the backend? Maven
WARNING! Deprecated: JHipster seems to be invoked using Yeoman command. Please use the JHipster CLI. Run jhipster <command> instead of yo jhipster:<command>
? Which *Framework* would you like to use for the client? No client
     info Using blueprint generator-jhipster-quarkus for common subgenerator
WARNING! Deprecated: JHipster seems to be invoked using Yeoman command. Please use the JHipster CLI. Run jhipster <command> instead of yo jhipster:<command>
? Would you like to enable internationalization support? Yes
? Please choose the native language of the application English
? Please choose additional languages to install 
WARNING! Deprecated: JHipster seems to be invoked using Yeoman command. Please use the JHipster CLI. Run jhipster <command> instead of yo jhipster:<command>
```

**Expected behavior**
No warnings

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by avdev4j** [comment] 2020-09-15 12:10
Yes it's sound strange for me as we use the JHipster CLI and not anything else.

**Comment by nshaw** [comment] 2020-09-15 12:15
I did some testing on it and I'm not understanding why the deprecation warnings show sometimes and not others, even in the same project. I'll try to put a bit more time into it today.

**Comment by avdev4j** [comment] 2020-09-16 09:17
Same here, I wonder if this can come from the npm link command. We should tried in a stable environment and install the blueprint with a clean installation (`npm i generator-jhipster-quarkus`).

**Comment by avdev4j** [comment] 2020-11-30 09:28
I suggest to close this one since it a bit hard to reproduce.

I have installed locally both JHipster and the blueprint and I can't reproduce warnings. I wonder if this can came from dev settings and npm link usage.

Anyway, let's close it and re-open if needed.

**Closed by avdev4j** 2020-11-30 09:28 UTC
Labels: bug, good first issue
