### ISSUE TITLE
Non compilable java code generated

### ISSUE THREAD

**Issue by sjaakd** [jhipster/generator-jhipster-quarkus#389] opened 2024-09-03 20:43 UTC
**Describe the bug**
* Spring dependency in quarkus code `RequestParam` in REST resource. Should this be `QueryParam` ?
* `JsonIgnore` (whithout import) on generated entity class

**To Reproduce**
Steps to reproduce the behavior. Use the following jdl file:

```
application {
  config {
    baseName productstructure
    packageName nl.gdn.psa
    applicationType monolith
    clientFramework angular
	packageName nl.gdn.psa
  }
  entities Portfolio, Product
}

entity Portfolio{
  name String
}

entity Product {
  name String
  type ProductType
  department String
  contact String
  functionalOwner String
  productOwner String
  description String
  reference String
}

relationship OneToMany {
  Product{parent} to Product
}

relationship OneToOne {
  Portfolio{product} to Product
}

enum ProductType {
  COMPOSITE,
  INFORMATION_PRODUCT,
  SOFTWARE
}
```

`./mvnw (on java 17) `

produces
```
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] source/product-structure/src/main/java/nl/gdn/psa/domain/Product.java:[51,6] cannot find symbol
  symbol:   class JsonIgnore
  location: class nl.gdn.psa.domain.Product
[ERROR] source/product-structure/src/main/java/nl/gdn/psa/web/rest/ProductResource.java:[100,42] cannot find symbol
  symbol:   class RequestParam
  location: class nl.gdn.psa.web.rest.ProductResource
```

If you decide to generate a `ServiceImpl` and DTO on  `Product` there will be as well one missing method on the service: `public List<ProductDTO> findAllWherePortfolioIsNull()`.  Also the `JsonIgnore` is there on the entity, while the entity is exposed via a DTO.

**Expected behavior**
working code?

**Comment by mraible** [comment] 2024-09-13 04:08
This might be fixed by https://github.com/jhipster/generator-jhipster-quarkus/pull/370.

**Comment by mraible** [comment] 2024-10-31 14:33
@mshima FYI: when I create an app with this JDL using the `main` branch, it prints a warning:

```
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: 'productstructure@0.0.1-SNAPSHOT',
npm warn EBADENGINE   required: { node: '>=22.11.0' },
npm warn EBADENGINE   current: { node: 'v20.18.0', npm: '10.9.0' }
npm warn EBADENGINE }
```

I'm not sure where this is coming from since `package.json` has the following:

```json
  "engines": {
    "node": ">=22.11.0"
  },
```

**Comment by mraible** [comment] 2024-10-31 14:34
I tried reproducing this issue with the `main` branch and there is a compilation failure:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.13.0:compile (default-compile) on project productstructure: Compilation failure
[ERROR] /Users/mraible/Downloads/quarkus/src/main/java/nl/gdn/psa/domain/Product.java:[55,6] cannot find symbol
[ERROR]   symbol:   class JsonIgnore
[ERROR]   location: class nl.gdn.psa.domain.Product
```

**Comment by mraible** [comment] 2024-10-31 14:39
@mshima This is what's generated:

```java
    @OneToOne(mappedBy = "product")
    @JsonIgnore
    public Portfolio portfolio;
```

The logic in `generators/quarkus/templates/src/main/java/_package_/_entityPackage_/domain/imports.ejs` doesn't seem to be working since the import is not included:

```ejs
for (idx in relationships) {
    if (relationships[idx].ownerSide === false && ['one-to-many', 'one-to-one', 'many-to-many'].includes(relationships[idx].relationshipType)) {
        importJsonIgnore = true;
    } else if (relationships[idx].relationshipType === 'many-to-one') {
        importJsonIgnoreProperties = true;
    }
    if (importJsonIgnore && importJsonIgnoreProperties) {
        break;
    }
}
```

**Closed** 2024-11-01 05:38 UTC
Labels: $$ bug-bounty $$, $100

**Comment by mraible** [comment] 2024-11-02 20:13
Bounty claimed: https://opencollective.com/generator-jhipster/expenses/226596
